version: '3.6'

services:
  db:
    image: mysql:latest
    container_name: database-${APP_NAME}
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    command:
      [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
      ]
    ports:
      - '3306:3306'
    volumes:
      - database:/var/lib/mysql

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wordpress-${APP_NAME}
    restart: unless-stopped
    env_file: .env
    ports:
      - '8001:80'
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_TABLE_PREFIX: am_wp_
      WORDPRESS_CONFIG_EXTRA: |
        define( 'FS_METHOD', 'direct' );
    volumes:
      - ./wordpress:/var/www/html
      - ./.docker/wordpress/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-${APP_NAME}
    restart: unless-stopped
    env_file: .env
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - phpmyadmin:/var/www/html

volumes:
  phpmyadmin:
    driver: local
  database:
    driver: local
